import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 })
const api = async (path, options = {}) => {
  const response = await fetch(path, { ...options, headers: { 'Content-Type': 'application/json', ...options.headers } })
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.error || 'Something went wrong. Please try again.')
  return data
}
async function shrinkImage(file) {
  const source = await new Promise((resolve, reject) => { const r = new FileReader(); r.onload = () => resolve(r.result); r.onerror = reject; r.readAsDataURL(file) })
  const image = await new Promise((resolve, reject) => { const img = new Image(); img.onload = () => resolve(img); img.onerror = reject; img.src = source })
  const max = 1000; const scale = Math.min(1, max / Math.max(image.width, image.height)); const canvas = document.createElement('canvas')
  canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale)
  canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height)
  return canvas.toDataURL('image/jpeg', 0.7)
}
function VolunteerForm() {
  const [volunteers, setVolunteers] = useState([]); const [selected, setSelected] = useState(''); const [type, setType] = useState('cash'); const [amount, setAmount] = useState(''); const [image, setImage] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { api('/api/volunteers').then(data => { setVolunteers(data); if (data[0]) setSelected(data[0]._id) }).catch(e => setStatus(e.message)) }, [])
  async function onImage(e) { const file = e.target.files?.[0]; if (!file) return; try { setImage(await shrinkImage(file)); setStatus('Receipt image ready.') } catch { setStatus('Could not read this image.') } }
  async function save(e) { e.preventDefault(); setStatus(''); setBusy(true); try { await api('/api/donations', { method: 'POST', body: JSON.stringify({ volunteerId: selected, type, amount, receiptImage: image }) }); setAmount(''); setImage(''); setStatus('Donation saved successfully. Thank you!') } catch (err) { setStatus(err.message) } finally { setBusy(false) } }
  return <main className="page"><header><div className="mark">♥</div><div><h1>Children Aadhar Foundation</h1><p>Donation collection</p></div><a href="/admin" className="admin-link">Admin</a></header><section className="card"><h2>Record a donation</h2><p className="hint">Select your name, collection type, and amount.</p><form onSubmit={save}><label>Volunteer</label><div className="chips">{volunteers.map(v => <button type="button" className={selected === v._id ? 'chip selected' : 'chip'} onClick={() => setSelected(v._id)} key={v._id}>{v.name}</button>)}</div><label>Collection type</label><select value={type} onChange={e => { setType(e.target.value); setImage('') }}><option value="cash">Cash</option><option value="upi">UPI</option></select><label>Amount (₹)</label><input inputMode="numeric" pattern="[0-9]*" type="number" min="1" required value={amount} onChange={e => setAmount(e.target.value)} placeholder="e.g. 500" />{type === 'upi' && <><label>UPI receipt image</label><input className="file" type="file" accept="image/*" capture="environment" required={!image} onChange={onImage} />{image && <img className="preview" src={image} alt="UPI receipt preview" />}</>}<button className="save" disabled={busy || !selected}>{busy ? 'Saving…' : 'Save donation'}</button></form>{status && <p className={status.includes('success') ? 'notice good' : 'notice'}>{status}</p>}</section><p className="footer">Every contribution helps build brighter futures.</p></main>
}
function Admin() {
  const [token, setToken] = useState(localStorage.getItem('caf-admin') || ''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [data, setData] = useState(null); const [volunteers, setVolunteers] = useState([]); const [name, setName] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('')
  const headers = useMemo(() => ({ Authorization: `Bearer ${token}` }), [token])
  const load = async () => { try { const query = new URLSearchParams(); if (from) query.set('from', from); if (to) query.set('to', to); const [dash, users] = await Promise.all([api(`/api/admin/dashboard?${query}`, { headers }), api('/api/admin/volunteers', { headers })]); setData(dash); setVolunteers(users) } catch (e) { setError(e.message); if (e.message.includes('sign in')) { localStorage.removeItem('caf-admin'); setToken('') } } }
  useEffect(() => { if (token) load() }, [token])
  async function login(e) { e.preventDefault(); setError(''); try { const { token: newToken } = await api('/api/admin/login', { method: 'POST', body: JSON.stringify({ password }) }); localStorage.setItem('caf-admin', newToken); setToken(newToken) } catch (e) { setError(e.message) } }
  async function add(e) { e.preventDefault(); try { await api('/api/admin/volunteers', { method: 'POST', headers, body: JSON.stringify({ name }) }); setName(''); load() } catch (e) { setError(e.message) } }
  async function remove(id) { if (!confirm('Remove this volunteer from the collection form?')) return; try { await api(`/api/admin/volunteers/${id}`, { method: 'DELETE', headers }); load() } catch (e) { setError(e.message) } }
  if (!token) return <main className="page compact"><header><div className="mark">♥</div><div><h1>Admin sign in</h1><p>Children Aadhar Foundation</p></div></header><section className="card"><form onSubmit={login}><label>Admin password</label><input type="password" autoFocus value={password} onChange={e => setPassword(e.target.value)} required /><button className="save">Sign in</button></form>{error && <p className="notice">{error}</p>}<a href="/" className="back">← Back to collection form</a></section></main>
  const totals = data?.totals || { total: 0, count: 0, cash: 0, upi: 0 }
  return <main className="page admin"><header><div className="mark">♥</div><div><h1>Collection dashboard</h1><p>Children Aadhar Foundation</p></div><button className="logout" onClick={() => { localStorage.removeItem('caf-admin'); setToken('') }}>Sign out</button></header><section className="filter"><label>From <input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>To <input type="date" value={to} onChange={e => setTo(e.target.value)} /></label><button onClick={load}>Apply</button></section>{error && <p className="notice">{error}</p>}<section className="stats"><div><span>Total collection</span><strong>{money.format(totals.total)}</strong></div><div><span>Donations</span><strong>{totals.count}</strong></div><div><span>Cash</span><strong>{money.format(totals.cash)}</strong></div><div><span>UPI</span><strong>{money.format(totals.upi)}</strong></div></section><div className="grid"><section className="card"><h2>Volunteer collections</h2><div className="table">{data?.byVolunteer.length ? data.byVolunteer.map(v => <div className="row" key={v._id}><span>{v._id}<small>{v.count} donations</small></span><b>{money.format(v.total)}</b></div>) : <p className="hint">No collections in this date range.</p>}</div></section><section className="card"><h2>Volunteers</h2><form className="add" onSubmit={add}><input value={name} onChange={e => setName(e.target.value)} placeholder="New volunteer name" required /><button>Add</button></form>{volunteers.map(v => <div className="row" key={v._id}><span>{v.name}{!v.active && <small>Removed</small>}</span>{v.active && <button className="remove" onClick={() => remove(v._id)}>Remove</button>}</div>)}</section></div><section className="card recent"><h2>Recent donations</h2>{data?.recent.map(d => <div className="row" key={d._id}><span>{d.volunteerName} · {d.type.toUpperCase()}<small>{new Date(d.collectedAt).toLocaleString('en-IN')}</small></span><b>{money.format(d.amount)}</b></div>)}</section></main>
}
createRoot(document.getElementById('root')).render(location.pathname.startsWith('/admin') ? <Admin /> : <VolunteerForm />)
